### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by fguendling** [sebastianreinig/latextemplate#1]
Sebastian hast du Lust mich als Contributor hinzuzufügen?

Ich habe das Template schon verwendet, und könnte eine Anleitung dazu ins Readme schreiben.

**Comment by sebastianreinig** [comment]
Klar :) Das wäre super. Ich hab das gerade eingestellt und hoffe, dass es geklappt hat. Wenn nicht meld dich noch mal.
